name: Todo workflow

on:
  push:
    branches:
    - release/* #.+ means one or more. release/.+ will not match release/


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo the branch name
      run: echo "the current branch ${{ github.ref_name }}"

    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: $${{ github.ref_name }}
    