name: Todo workflow

on:
  - push
    #branches:
    #- 'release/*'


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      #with:
       # ref: 'release/*'
    