name: Todo workflow

on:
  push:
    branches:
    - "release/*" #[a-zA-Z0-9]+ means one or more of the preceding characters (a-z, A-Z or 0-9). 
                #release/[a-zA-Z0-9]+ will not match release/


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo the branch name
      run: echo "the current branch ${{ github.ref_name }}"

    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: $${{ github.ref_name }}
    