name: Todo workflow

on:
  push:
    branches:
    - "release" #[a-zA-Z0-9]+ means one or more of the preceding characters (a-z, A-Z or 0-9). #release/[a-zA-Z0-9]+ will not match release/

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo the branch name
      run: echo "the current branch ${{ github.ref_name }}"

    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: Deploy to vercel
      uses: amondnet/vercel-action@v25.1.0
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        github-token: ${{ secrets.GH_TOKEN }} #Optional
        vercel-org-id: ${{ secrets.ORG_ID }}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID }} #Required 
        vercel-args: '--prod'